# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Dev/FED

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Dev/FED

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/root/miniconda3/envs/fed_env/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Dev/FED/CMakeFiles /root/Dev/FED//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Dev/FED/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fed_cuda

# Build rule for target.
fed_cuda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fed_cuda
.PHONY : fed_cuda

# fast build rule for target.
fed_cuda/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_cuda.dir/build.make CMakeFiles/fed_cuda.dir/build
.PHONY : fed_cuda/fast

#=============================================================================
# Target rules for targets named fed_server

# Build rule for target.
fed_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fed_server
.PHONY : fed_server

# fast build rule for target.
fed_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/build
.PHONY : fed_server/fast

#=============================================================================
# Target rules for targets named fed_client

# Build rule for target.
fed_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fed_client
.PHONY : fed_client

# fast build rule for target.
fed_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/build
.PHONY : fed_client/fast

src/fed/aes_crypto.o: src/fed/aes_crypto.cpp.o
.PHONY : src/fed/aes_crypto.o

# target to build an object file
src/fed/aes_crypto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/aes_crypto.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/aes_crypto.cpp.o
.PHONY : src/fed/aes_crypto.cpp.o

src/fed/aes_crypto.i: src/fed/aes_crypto.cpp.i
.PHONY : src/fed/aes_crypto.i

# target to preprocess a source file
src/fed/aes_crypto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/aes_crypto.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/aes_crypto.cpp.i
.PHONY : src/fed/aes_crypto.cpp.i

src/fed/aes_crypto.s: src/fed/aes_crypto.cpp.s
.PHONY : src/fed/aes_crypto.s

# target to generate assembly for a file
src/fed/aes_crypto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/aes_crypto.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/aes_crypto.cpp.s
.PHONY : src/fed/aes_crypto.cpp.s

src/fed/audit_logger.o: src/fed/audit_logger.cpp.o
.PHONY : src/fed/audit_logger.o

# target to build an object file
src/fed/audit_logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/audit_logger.cpp.o
.PHONY : src/fed/audit_logger.cpp.o

src/fed/audit_logger.i: src/fed/audit_logger.cpp.i
.PHONY : src/fed/audit_logger.i

# target to preprocess a source file
src/fed/audit_logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/audit_logger.cpp.i
.PHONY : src/fed/audit_logger.cpp.i

src/fed/audit_logger.s: src/fed/audit_logger.cpp.s
.PHONY : src/fed/audit_logger.s

# target to generate assembly for a file
src/fed/audit_logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/audit_logger.cpp.s
.PHONY : src/fed/audit_logger.cpp.s

src/fed/auth_manager.o: src/fed/auth_manager.cpp.o
.PHONY : src/fed/auth_manager.o

# target to build an object file
src/fed/auth_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/auth_manager.cpp.o
.PHONY : src/fed/auth_manager.cpp.o

src/fed/auth_manager.i: src/fed/auth_manager.cpp.i
.PHONY : src/fed/auth_manager.i

# target to preprocess a source file
src/fed/auth_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/auth_manager.cpp.i
.PHONY : src/fed/auth_manager.cpp.i

src/fed/auth_manager.s: src/fed/auth_manager.cpp.s
.PHONY : src/fed/auth_manager.s

# target to generate assembly for a file
src/fed/auth_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/auth_manager.cpp.s
.PHONY : src/fed/auth_manager.cpp.s

src/fed/client.o: src/fed/client.cpp.o
.PHONY : src/fed/client.o

# target to build an object file
src/fed/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/client.cpp.o
.PHONY : src/fed/client.cpp.o

src/fed/client.i: src/fed/client.cpp.i
.PHONY : src/fed/client.i

# target to preprocess a source file
src/fed/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/client.cpp.i
.PHONY : src/fed/client.cpp.i

src/fed/client.s: src/fed/client.cpp.s
.PHONY : src/fed/client.s

# target to generate assembly for a file
src/fed/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/client.cpp.s
.PHONY : src/fed/client.cpp.s

src/fed/client_main.o: src/fed/client_main.cpp.o
.PHONY : src/fed/client_main.o

# target to build an object file
src/fed/client_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/client_main.cpp.o
.PHONY : src/fed/client_main.cpp.o

src/fed/client_main.i: src/fed/client_main.cpp.i
.PHONY : src/fed/client_main.i

# target to preprocess a source file
src/fed/client_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/client_main.cpp.i
.PHONY : src/fed/client_main.cpp.i

src/fed/client_main.s: src/fed/client_main.cpp.s
.PHONY : src/fed/client_main.s

# target to generate assembly for a file
src/fed/client_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/client_main.cpp.s
.PHONY : src/fed/client_main.cpp.s

src/fed/crypto.o: src/fed/crypto.cpp.o
.PHONY : src/fed/crypto.o

# target to build an object file
src/fed/crypto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/crypto.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/crypto.cpp.o
.PHONY : src/fed/crypto.cpp.o

src/fed/crypto.i: src/fed/crypto.cpp.i
.PHONY : src/fed/crypto.i

# target to preprocess a source file
src/fed/crypto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/crypto.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/crypto.cpp.i
.PHONY : src/fed/crypto.cpp.i

src/fed/crypto.s: src/fed/crypto.cpp.s
.PHONY : src/fed/crypto.s

# target to generate assembly for a file
src/fed/crypto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/crypto.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/crypto.cpp.s
.PHONY : src/fed/crypto.cpp.s

src/fed/data_preprocessor.o: src/fed/data_preprocessor.cpp.o
.PHONY : src/fed/data_preprocessor.o

# target to build an object file
src/fed/data_preprocessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/data_preprocessor.cpp.o
.PHONY : src/fed/data_preprocessor.cpp.o

src/fed/data_preprocessor.i: src/fed/data_preprocessor.cpp.i
.PHONY : src/fed/data_preprocessor.i

# target to preprocess a source file
src/fed/data_preprocessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/data_preprocessor.cpp.i
.PHONY : src/fed/data_preprocessor.cpp.i

src/fed/data_preprocessor.s: src/fed/data_preprocessor.cpp.s
.PHONY : src/fed/data_preprocessor.s

# target to generate assembly for a file
src/fed/data_preprocessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/data_preprocessor.cpp.s
.PHONY : src/fed/data_preprocessor.cpp.s

src/fed/server.o: src/fed/server.cpp.o
.PHONY : src/fed/server.o

# target to build an object file
src/fed/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/server.cpp.o
.PHONY : src/fed/server.cpp.o

src/fed/server.i: src/fed/server.cpp.i
.PHONY : src/fed/server.i

# target to preprocess a source file
src/fed/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/server.cpp.i
.PHONY : src/fed/server.cpp.i

src/fed/server.s: src/fed/server.cpp.s
.PHONY : src/fed/server.s

# target to generate assembly for a file
src/fed/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/server.cpp.s
.PHONY : src/fed/server.cpp.s

src/fed/server_main.o: src/fed/server_main.cpp.o
.PHONY : src/fed/server_main.o

# target to build an object file
src/fed/server_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/server_main.cpp.o
.PHONY : src/fed/server_main.cpp.o

src/fed/server_main.i: src/fed/server_main.cpp.i
.PHONY : src/fed/server_main.i

# target to preprocess a source file
src/fed/server_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/server_main.cpp.i
.PHONY : src/fed/server_main.cpp.i

src/fed/server_main.s: src/fed/server_main.cpp.s
.PHONY : src/fed/server_main.s

# target to generate assembly for a file
src/fed/server_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/server_main.cpp.s
.PHONY : src/fed/server_main.cpp.s

src/fed/tls_connection.o: src/fed/tls_connection.cpp.o
.PHONY : src/fed/tls_connection.o

# target to build an object file
src/fed/tls_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/tls_connection.cpp.o
.PHONY : src/fed/tls_connection.cpp.o

src/fed/tls_connection.i: src/fed/tls_connection.cpp.i
.PHONY : src/fed/tls_connection.i

# target to preprocess a source file
src/fed/tls_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/tls_connection.cpp.i
.PHONY : src/fed/tls_connection.cpp.i

src/fed/tls_connection.s: src/fed/tls_connection.cpp.s
.PHONY : src/fed/tls_connection.s

# target to generate assembly for a file
src/fed/tls_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/tls_connection.cpp.s
.PHONY : src/fed/tls_connection.cpp.s

src/fed/tls_connection_new.o: src/fed/tls_connection_new.cpp.o
.PHONY : src/fed/tls_connection_new.o

# target to build an object file
src/fed/tls_connection_new.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/tls_connection_new.cpp.o
.PHONY : src/fed/tls_connection_new.cpp.o

src/fed/tls_connection_new.i: src/fed/tls_connection_new.cpp.i
.PHONY : src/fed/tls_connection_new.i

# target to preprocess a source file
src/fed/tls_connection_new.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/tls_connection_new.cpp.i
.PHONY : src/fed/tls_connection_new.cpp.i

src/fed/tls_connection_new.s: src/fed/tls_connection_new.cpp.s
.PHONY : src/fed/tls_connection_new.s

# target to generate assembly for a file
src/fed/tls_connection_new.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_server.dir/build.make CMakeFiles/fed_server.dir/src/fed/tls_connection_new.cpp.s
.PHONY : src/fed/tls_connection_new.cpp.s

src/fed/union_find.o: src/fed/union_find.cpp.o
.PHONY : src/fed/union_find.o

# target to build an object file
src/fed/union_find.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/union_find.cpp.o
.PHONY : src/fed/union_find.cpp.o

src/fed/union_find.i: src/fed/union_find.cpp.i
.PHONY : src/fed/union_find.i

# target to preprocess a source file
src/fed/union_find.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/union_find.cpp.i
.PHONY : src/fed/union_find.cpp.i

src/fed/union_find.s: src/fed/union_find.cpp.s
.PHONY : src/fed/union_find.s

# target to generate assembly for a file
src/fed/union_find.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fed_client.dir/build.make CMakeFiles/fed_client.dir/src/fed/union_find.cpp.s
.PHONY : src/fed/union_find.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fed_client"
	@echo "... fed_cuda"
	@echo "... fed_server"
	@echo "... src/fed/aes_crypto.o"
	@echo "... src/fed/aes_crypto.i"
	@echo "... src/fed/aes_crypto.s"
	@echo "... src/fed/audit_logger.o"
	@echo "... src/fed/audit_logger.i"
	@echo "... src/fed/audit_logger.s"
	@echo "... src/fed/auth_manager.o"
	@echo "... src/fed/auth_manager.i"
	@echo "... src/fed/auth_manager.s"
	@echo "... src/fed/client.o"
	@echo "... src/fed/client.i"
	@echo "... src/fed/client.s"
	@echo "... src/fed/client_main.o"
	@echo "... src/fed/client_main.i"
	@echo "... src/fed/client_main.s"
	@echo "... src/fed/crypto.o"
	@echo "... src/fed/crypto.i"
	@echo "... src/fed/crypto.s"
	@echo "... src/fed/data_preprocessor.o"
	@echo "... src/fed/data_preprocessor.i"
	@echo "... src/fed/data_preprocessor.s"
	@echo "... src/fed/server.o"
	@echo "... src/fed/server.i"
	@echo "... src/fed/server.s"
	@echo "... src/fed/server_main.o"
	@echo "... src/fed/server_main.i"
	@echo "... src/fed/server_main.s"
	@echo "... src/fed/tls_connection.o"
	@echo "... src/fed/tls_connection.i"
	@echo "... src/fed/tls_connection.s"
	@echo "... src/fed/tls_connection_new.o"
	@echo "... src/fed/tls_connection_new.i"
	@echo "... src/fed/tls_connection_new.s"
	@echo "... src/fed/union_find.o"
	@echo "... src/fed/union_find.i"
	@echo "... src/fed/union_find.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

